import { NextRequest, NextResponse } from 'next/server';
import type { ChecklistItem, ChecklistItemStatus, ChecklistItemType } from '@admissions-compass/shared';

// Mock checklist items for various applications
const mockChecklistItems: Record<string, ChecklistItem[]> = {
  'app-001': [
    {
      id: 'ci-001',
      application_id: 'app-001',
      template_item_id: 'ti-003',
      title: 'Submit Application Form',
      description: 'Complete and submit the full application form.',
      item_type: 'form_submission' as ChecklistItemType,
      is_required: true,
      sort_order: 0,
      status: 'completed' as ChecklistItemStatus,
      due_date: null,
      completed_at: '2025-11-15T10:30:00Z',
      completed_by: 'user-parent-001',
      config: { form_id: '00000000-0000-0000-0000-000000000302' },
      data: {},
      created_at: '2025-11-01T00:00:00Z',
      updated_at: '2025-11-15T10:30:00Z',
    },
    {
      id: 'ci-002',
      application_id: 'app-001',
      template_item_id: 'ti-004',
      title: 'Upload Birth Certificate',
      description: 'Upload a certified copy of the student birth certificate.',
      item_type: 'document_upload' as ChecklistItemType,
      is_required: true,
      sort_order: 1,
      status: 'completed' as ChecklistItemStatus,
      due_date: null,
      completed_at: '2025-11-12T14:00:00Z',
      completed_by: 'user-parent-001',
      config: { accepted_types: ['pdf', 'jpg', 'png'], max_size_mb: 10 },
      data: { file_name: 'birth_cert_emma.pdf', file_size: 245000 },
      created_at: '2025-11-01T00:00:00Z',
      updated_at: '2025-11-12T14:00:00Z',
    },
    {
      id: 'ci-003',
      application_id: 'app-001',
      template_item_id: 'ti-005',
      title: 'Upload Immunization Records',
      description: 'Provide current immunization records from your pediatrician.',
      item_type: 'document_upload' as ChecklistItemType,
      is_required: true,
      sort_order: 2,
      status: 'completed' as ChecklistItemStatus,
      due_date: '2026-01-15',
      completed_at: '2025-12-20T09:00:00Z',
      completed_by: 'user-parent-001',
      config: { accepted_types: ['pdf', 'jpg', 'png'], max_size_mb: 10 },
      data: { file_name: 'immunizations_emma.pdf', file_size: 178000 },
      created_at: '2025-11-01T00:00:00Z',
      updated_at: '2025-12-20T09:00:00Z',
    },
    {
      id: 'ci-004',
      application_id: 'app-001',
      template_item_id: 'ti-006',
      title: 'Request Teacher Recommendation',
      description: 'Request a recommendation letter from a current teacher.',
      item_type: 'recommendation' as ChecklistItemType,
      is_required: true,
      sort_order: 3,
      status: 'submitted' as ChecklistItemStatus,
      due_date: '2025-12-22',
      completed_at: null,
      completed_by: null,
      config: { form_id: '00000000-0000-0000-0000-000000000303' },
      data: { recommender_name: 'Mrs. Davis', recommender_email: 'davis@school.edu', sent_at: '2025-11-10T00:00:00Z' },
      created_at: '2025-11-01T00:00:00Z',
      updated_at: '2025-12-01T00:00:00Z',
    },
    {
      id: 'ci-005',
      application_id: 'app-001',
      template_item_id: 'ti-007',
      title: 'Pay Application Fee',
      description: 'Submit the non-refundable application fee of $75.',
      item_type: 'payment' as ChecklistItemType,
      is_required: true,
      sort_order: 4,
      status: 'completed' as ChecklistItemStatus,
      due_date: null,
      completed_at: '2025-11-02T08:15:00Z',
      completed_by: 'user-parent-001',
      config: { payment_amount: 7500, currency: 'usd', description: 'Application Fee' },
      data: { stripe_payment_id: 'pi_mock_001', amount_paid: 7500 },
      created_at: '2025-11-01T00:00:00Z',
      updated_at: '2025-11-02T08:15:00Z',
    },
    {
      id: 'ci-006',
      application_id: 'app-001',
      template_item_id: 'ti-008',
      title: 'Schedule Student Assessment',
      description: 'Book a time slot for the student readiness assessment.',
      item_type: 'assessment' as ChecklistItemType,
      is_required: true,
      sort_order: 5,
      status: 'not_started' as ChecklistItemStatus,
      due_date: '2025-12-29',
      completed_at: null,
      completed_by: null,
      config: { event_calendar_id: 'cal-002' },
      data: {},
      created_at: '2025-11-01T00:00:00Z',
      updated_at: '2025-11-01T00:00:00Z',
    },
  ],
  'app-002': [
    {
      id: 'ci-007',
      application_id: 'app-002',
      template_item_id: 'ti-003',
      title: 'Submit Application Form',
      description: 'Complete and submit the full application form.',
      item_type: 'form_submission' as ChecklistItemType,
      is_required: true,
      sort_order: 0,
      status: 'in_progress' as ChecklistItemStatus,
      due_date: null,
      completed_at: null,
      completed_by: null,
      config: { form_id: '00000000-0000-0000-0000-000000000302' },
      data: {},
      created_at: '2025-12-01T00:00:00Z',
      updated_at: '2025-12-10T00:00:00Z',
    },
    {
      id: 'ci-008',
      application_id: 'app-002',
      template_item_id: 'ti-004',
      title: 'Upload Birth Certificate',
      description: 'Upload a certified copy of the student birth certificate.',
      item_type: 'document_upload' as ChecklistItemType,
      is_required: true,
      sort_order: 1,
      status: 'not_started' as ChecklistItemStatus,
      due_date: null,
      completed_at: null,
      completed_by: null,
      config: { accepted_types: ['pdf', 'jpg', 'png'], max_size_mb: 10 },
      data: {},
      created_at: '2025-12-01T00:00:00Z',
      updated_at: '2025-12-01T00:00:00Z',
    },
    {
      id: 'ci-009',
      application_id: 'app-002',
      template_item_id: 'ti-007',
      title: 'Pay Application Fee',
      description: 'Submit the non-refundable application fee of $75.',
      item_type: 'payment' as ChecklistItemType,
      is_required: true,
      sort_order: 2,
      status: 'not_started' as ChecklistItemStatus,
      due_date: null,
      completed_at: null,
      completed_by: null,
      config: { payment_amount: 7500, currency: 'usd', description: 'Application Fee' },
      data: {},
      created_at: '2025-12-01T00:00:00Z',
      updated_at: '2025-12-01T00:00:00Z',
    },
  ],
};

let checklistItems = { ...mockChecklistItems };

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const items = checklistItems[id] || [];

  return NextResponse.json({
    data: items.sort((a, b) => a.sort_order - b.sort_order),
  });
}
